- name: print the variables
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: "im learning ansible {{NAME}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"